### ISSUE TITLE
Prac 5, Task 3 - Error on fitchfork

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/black-fitch#24]
See [forum](http://www.cs.up.ac.za/forum/index.php?t=msg&th=95&start=0&) for active discussion.

Will have to wait until problem is resolved on their side before confirming the validity of Task 3 tests introduced by #22 

```
Compile WARNING => Possible compile warnings and/or errors follow, try to get rid of them.
make: *** No rule to make target 'Exception.h', needed by 'main'.  Stop.

Compile FAILURE
Execute FAILED
Test case '1' => Produced 101 bytes of output, exit code 2

make: ./main: Command not found
makefile:8: recipe for target 'run' failed
make: *** [run] Error 127

FAIL Test 1: Error in empty string exception.
FAIL Test 2: Error in char not found exception.
FAIL Test 3: Error in empty result exception.
FAIL Test 4: Error in unequal size exception.
FAIL Test 5: Error in char not found exception.
FAIL Test 6: Error in empty string exception.
FAIL Test 7: Error in empty string exception.
FAIL Test 8: Error in empty result exception.
FAIL Test 9: Error in out of bounds exception.
FAIL Test 10: Error in out of bounds exception.
```

**Comment by egeldenhuys** [comment]
The previous error has been silently replaced with:

```
Compile WARNING => Possible compile warnings and/or errors follow, try to get rid of them.
In file included from CharString.cpp:4:0:
CharString.h:5:34: fatal error: EmptyResultException.h: No such file or directory
compilation terminated.
makefile:5: recipe for target 'CharString' failed
make: *** [CharString] Error 1

Compile FAILURE
Execute FAILED
Test case '1' => Produced 101 bytes of output, exit code 2

make: ./main: Command not found
makefile:8: recipe for target 'run' failed
make: *** [run] Error 127

FAIL Test 1: Error in empty string exception.
FAIL Test 2: Error in char not found exception.
FAIL Test 3: Error in empty result exception.
FAIL Test 4: Error in unequal size exception.
FAIL Test 5: Error in char not found exception.
FAIL Test 6: Error in empty string exception.
FAIL Test 7: Error in empty string exception.
FAIL Test 8: Error in empty result exception.
FAIL Test 9: Error in out of bounds exception.
FAIL Test 10: Error in out of bounds exception.
```

**Comment by egeldenhuys** [comment]
Right, sorry. I was following the specifications too carefully. Include the missing file:

```
9/10

FAIL Test 5: Error in char not found exception.
```
